import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";

import Navbar from "../components/navbar";
import Card from "@/components/Card";
import Banner from "@/components/banner";
import articles from "../data/blogs.json";

const inter = Inter({ subsets: ["latin"] });

export async function getStaticProps(context: any) {
  return {
    props: {
      articles,
    },
  };
}

export default function Home(props: any) {
  console.log("props", props);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/*         
          <Navbar /> */}
        <Banner />

        {articles.map((article) => {
          return (
            <Card
              key={article.id}
              name={article.name}
              imgUrl={article.imgUrl}
              href={article.href}
              author={article.author}
              prompt={article.prompt}
            />
          );
        })}
      </main>
    </>
  );
}
